SELECT

      NAME_TABLE.NAME,
      COUNT(RESULT_TABLE.NAME_ID)
    
    
FROM 
     NAME_TABLE
     JOIN
     RESULT_TABLE
     ON RESULT_TABLE.NAME_ID=NAME_TABLE.NAME_ID
     
GROUP BY 
      RESULT_TABLE.NAME_ID
     
HAVING
     COUNT(RESULT_TABLE.NAME_ID)>2;
