SELECT
    
    NAME_TABLE.NAME,
    RESULT_TABLE.CATEGORY,
    AVG(RESULT_TABLE.SCORE)
     
FROM 
     RESULT_TABLE
     JOIN
     NAME_TABLE
     ON  RESULT_TABLE.NAME_ID=NAME_TABLE.NAME_ID

GROUP BY NAME_TABLE.NAME,
          RESULT_TABLE.CATEGORY
  
