UPDATE
     RESULT_TABLE

SET  NAME_TABLE.rank="C"


FROM 
     RESULT_TABLE
     INNER JOIN
     NAME_TABLE
     ON  RESULT_TABLE.NAME_ID=NAME_TABLE.NAME_ID

where 
     RESULT_TABLE.playdate>='2022-04-01'
     AND RESULT_TABLE.playdate<='20220-04-30'
     AND AVG(RESULT_TABLE.score)<=10;
